selftests: mptcp: pm: fix pm_nl_ctl build errors with old glibc
Compiling pm_nl_ctl on older versions of glibc will report the following
errors:

'''
  CC       pm_nl_ctl
pm_nl_ctl.c: In function 'capture_events':
pm_nl_ctl.c:204:53: error: 'MPTCP_PM_EV_FLAG_DENY_JOIN_ID0' undeclared (first use in this function)
  204 |                                         if (flags & MPTCP_PM_EV_FLAG_DENY_JOIN_ID0)
      |                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
pm_nl_ctl.c:204:53: note: each undeclared identifier is reported only once for each function it appears in
pm_nl_ctl.c:206:53: error: 'MPTCP_PM_EV_FLAG_SERVER_SIDE' undeclared (first use in this function); did you mean 'MPTCP_ATTR_SERVER_SIDE'?
  206 |                                         if (flags & MPTCP_PM_EV_FLAG_SERVER_SIDE)
      |                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                     MPTCP_ATTR_SERVER_SIDE
'''

To fix this, this patch redefines MPTCP_PM_EV_FLAG_DENY_JOIN_ID0 and
MPTCP_PM_EV_FLAG_SERVER_SIDE in pm_nl_ctl.c.

Fixes: 24733e193a0d ("selftests: mptcp: userspace pm: validate deny-join-id0 flag")
Fixes: 198c12e28b51 ("selftests: mptcp: pm: get server-side flag")
Signed-off-by: Geliang Tang <tanggeliang@kylinos.cn>
Message-ID: <092fc76415deb1b45da5bb691ef6069fbab7dd09.1758591744.git.tanggeliang@kylinos.cn>