Squash to "mptcp: borrow forward memory from subflow"
Due to a previous revert:

  bf39160c4218 ("Revert "mptcp: do not drop partial packets"")

The issue:

  net/mptcp/protocol.c: In function '__mptcp_move_skb':
  net/mptcp/protocol.c:408:1: error: label 'drop' defined but not used [-Werror=unused-label]
    408 | drop:
        | ^~~~

Signed-off-by: Matthieu Baerts (NGI0) <matttbe@kernel.org>