Squash to "selftests/bpf: test bpf_skc_to_mptcp_sock"
Drop bpf_mptcp_helpers.h, squash into bpf_tcp_helpers.h (Andrii)

1

CONFLICT (modify/delete): tools/testing/selftests/bpf/bpf_mptcp_helpers.h deleted in HEAD and modified in 8996b41ffcd2 (selftests/bpf: verify token of struct mptcp_sock).  Version 8996b41ffcd2 (selftests/bpf: verify token of struct mptcp_sock) of tools/testing/selftests/bpf/bpf_mptcp_helpers.h left in tree.
Auto-merging tools/testing/selftests/bpf/progs/mptcp_sock.c
error: could not apply 8996b41ffcd2... selftests/bpf: verify token of struct mptcp_sock

cat tools/testing/selftests/bpf/bpf_tcp_helpers.h:

'''
extern void tcp_cong_avoid_ai(struct tcp_sock *tp, __u32 w, __u32 acked) __ksym;

struct mptcp_sock {
	struct inet_connection_sock	sk;

	__u32		token;
} __attribute__((preserve_access_index));

'''

git add tools/testing/selftests/bpf/bpf_tcp_helpers.h
git rm tools/testing/selftests/bpf/bpf_mptcp_helpers.h

2

CONFLICT (modify/delete): tools/testing/selftests/bpf/bpf_mptcp_helpers.h deleted in HEAD and modified in 57dcfb6f61ec (selftests/bpf: verify ca_name of struct mptcp_sock).  Version 57dcfb6f61ec (selftests/bpf: verify ca_name of struct mptcp_sock) of tools/testing/selftests/bpf/bpf_mptcp_helpers.h left in tree.
Auto-merging tools/testing/selftests/bpf/bpf_tcp_helpers.h
Auto-merging tools/testing/selftests/bpf/progs/mptcp_sock.c
error: could not apply 57dcfb6f61ec... selftests/bpf: verify ca_name of struct mptcp_sock

cat tools/testing/selftests/bpf/bpf_tcp_helpers.h:

'''
extern void tcp_cong_avoid_ai(struct tcp_sock *tp, __u32 w, __u32 acked) __ksym;

struct mptcp_sock {
	struct inet_connection_sock	sk;

	__u32		token;
	char		ca_name[TCP_CA_NAME_MAX];
} __attribute__((preserve_access_index));

'''

git add tools/testing/selftests/bpf/bpf_tcp_helpers.h
git rm tools/testing/selftests/bpf/bpf_mptcp_helpers.h

3

CONFLICT (modify/delete): tools/testing/selftests/bpf/bpf_mptcp_helpers.h deleted in HEAD and modified in 416cb433f1df (selftests/bpf: verify first of struct mptcp_sock).  Version 416cb433f1df (selftests/bpf: verify first of struct mptcp_sock) of tools/testing/selftests/bpf/bpf_mptcp_helpers.h left in tree.
Auto-merging tools/testing/selftests/bpf/progs/mptcp_sock.c
error: could not apply 416cb433f1df... selftests/bpf: verify first of struct mptcp_sock

cat tools/testing/selftests/bpf/bpf_tcp_helpers.h:

'''
extern void tcp_cong_avoid_ai(struct tcp_sock *tp, __u32 w, __u32 acked) __ksym;

struct mptcp_sock {
	struct inet_connection_sock	sk;

	__u32		token;
	struct sock	*first;
	char		ca_name[TCP_CA_NAME_MAX];
} __attribute__((preserve_access_index));

'''

git add tools/testing/selftests/bpf/bpf_tcp_helpers.h
git rm tools/testing/selftests/bpf/bpf_mptcp_helpers.h

4

CONFLICT (modify/delete): tools/testing/selftests/bpf/bpf_mptcp_helpers.h deleted in HEAD and modified in 74d3c74494e6 (mptcp: add struct mptcp_sched_ops).  Version 74d3c74494e6 (mptcp: add struct mptcp_sched_ops) of tools/testing/selftests/bpf/bpf_mptcp_helpers.h left in tree.
error: could not apply 74d3c74494e6... mptcp: add struct mptcp_sched_ops

cat tools/testing/selftests/bpf/bpf_tcp_helpers.h:

'''
extern void tcp_cong_avoid_ai(struct tcp_sock *tp, __u32 w, __u32 acked) __ksym;

struct mptcp_sched_data {
	struct sock	*sock;
	bool		call_again;
};

struct mptcp_sched_ops {
	char name[MPTCP_SCHED_NAME_MAX];

	void (*init)(const struct mptcp_sock *msk);
	void (*release)(const struct mptcp_sock *msk);

	void (*get_subflow)(const struct mptcp_sock *msk, bool reinject,
			    struct mptcp_sched_data *data);
	void *owner;
};

struct mptcp_sock {
	struct inet_connection_sock	sk;

	__u32		token;
	struct sock	*first;
	char		ca_name[TCP_CA_NAME_MAX];
} __attribute__((preserve_access_index));

'''

git add tools/testing/selftests/bpf/bpf_tcp_helpers.h
git rm tools/testing/selftests/bpf/bpf_mptcp_helpers.h

5

CONFLICT (modify/delete): tools/testing/selftests/bpf/bpf_mptcp_helpers.h deleted in HEAD and modified in 1b3d7a5f1f10 (mptcp: add sched in mptcp_sock).  Version 1b3d7a5f1f10 (mptcp: add sched in mptcp_sock) of tools/testing/selftests/bpf/bpf_mptcp_helpers.h left in tree.
error: could not apply 1b3d7a5f1f10... mptcp: add sched in mptcp_sock

cat tools/testing/selftests/bpf/bpf_tcp_helpers.h:

'''
extern void tcp_cong_avoid_ai(struct tcp_sock *tp, __u32 w, __u32 acked) __ksym;

struct mptcp_sched_data {
	struct sock	*sock;
	bool		call_again;
};

struct mptcp_sched_ops {
	char name[MPTCP_SCHED_NAME_MAX];

	void (*init)(const struct mptcp_sock *msk);
	void (*release)(const struct mptcp_sock *msk);

	void (*get_subflow)(const struct mptcp_sock *msk, bool reinject,
			    struct mptcp_sched_data *data);
	void *owner;
};

struct mptcp_sock {
	struct inet_connection_sock	sk;

	__u32		token;
	struct sock	*first;
	struct mptcp_sched_ops *sched;
	char		ca_name[TCP_CA_NAME_MAX];
} __attribute__((preserve_access_index));

'''

git add tools/testing/selftests/bpf/bpf_tcp_helpers.h
git rm tools/testing/selftests/bpf/bpf_mptcp_helpers.h

Signed-off-by: Geliang Tang <geliang.tang@suse.com>
Signed-off-by: Matthieu Baerts <matthieu.baerts@tessares.net>