Squash-to "bpf: Add bpf_mptcp_sched_ops"
The BPF API around btf_struct_access() has been modified recently, see
commit 6728aea7216c ("bpf: Refactor btf_struct_access").

Adaptations have been done, similar to what was done in the mentioned
commit, e.g. by looking at changes around bpf_tcp_ca_btf_struct_access().

Without this modification, we have compilation errors:

    net/mptcp/bpf.c: In function 'bpf_mptcp_sched_btf_struct_access':
    net/mptcp/bpf.c:46:47: error: passing argument 2 of 'btf_struct_access' from incompatible pointer type [-Werror=incompatible-pointer-types]
     46 |                 return btf_struct_access(log, btf, t, off, size, atype,
        |                                               ^~~
        |                                               |
        |                                               const struct btf *
  In file included from   net/mptcp/bpf.c:12:
    include/linux/bpf.h:2155:51: note: expected 'const struct bpf_reg_state *' but argument is of type 'const struct btf *'
   2155 |                       const struct bpf_reg_state *reg,
        |                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
    net/mptcp/bpf.c:46:52: error: passing argument 3 of 'btf_struct_access' makes integer from pointer without a cast [-Werror=int-conversion]
     46 |                 return btf_struct_access(log, btf, t, off, size, atype,
        |                                                    ^
        |                                                    |
        |                                                    const struct btf_type *
  In file included from   net/mptcp/bpf.c:12:
    include/linux/bpf.h:2156:27: note: expected 'int' but argument is of type 'const struct btf_type *'
   2156 |                       int off, int size, enum bpf_access_type atype,
        |                       ~~~~^~~
    net/mptcp/bpf.c:46:66: error: incompatible type for argument 6 of 'btf_struct_access'
     46 |                 return btf_struct_access(log, btf, t, off, size, atype,
        |                                                                  ^~~~~
        |                                                                  |
        |                                                                  enum bpf_access_type
  In file included from   net/mptcp/bpf.c:12:
    include/linux/bpf.h:2157:28: note: expected 'u32 *' {aka 'unsigned int *'} but argument is of type 'enum bpf_access_type'
   2157 |                       u32 *next_btf_id, enum bpf_type_flag *flag);
        |                       ~~~~~^~~~~~~~~~~
    net/mptcp/bpf.c:46:24: error: too many arguments to function 'btf_struct_access'
     46 |                 return btf_struct_access(log, btf, t, off, size, atype,
        |                        ^~~~~~~~~~~~~~~~~
  In file included from   net/mptcp/bpf.c:12:
    include/linux/bpf.h:2154:5: note: declared here
   2154 | int btf_struct_access(struct bpf_verifier_log *log,
        |     ^~~~~~~~~~~~~~~~~
    net/mptcp/bpf.c: At top level:
    net/mptcp/bpf.c:76:35: error: initialization of 'int (*)(struct bpf_verifier_log *, const struct bpf_reg_state *, int,  int,  enum bpf_access_type,  u32 *, enum bpf_type_flag *)' {aka 'int (*)(struct bpf_verifier_log *, const struct bpf_reg_state *, int,  int,  enum bpf_access_type,  unsigned int *, enum bpf_type_flag *)'} from incompatible pointer type 'int (*)(struct bpf_verifier_log *, const struct btf *, const struct btf_type *, int,  int,  enum bpf_access_type,  u32 *, enum bpf_type_flag *)' {aka 'int (*)(struct bpf_verifier_log *, const struct btf *, const struct btf_type *, int,  int,  enum bpf_access_type,  unsigned int *, enum bpf_type_flag *)'} [-Werror=incompatible-pointer-types]
     76 |         .btf_struct_access      = bpf_mptcp_sched_btf_struct_access,
        |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    net/mptcp/bpf.c:76:35: note: (near initialization for 'bpf_mptcp_sched_verifier_ops.btf_struct_access')

Fixes: 6728aea7216c ("bpf: Refactor btf_struct_access")
Link: https://cirrus-ci.com/task/5509843558072320?logs=test#L3300-L3262
Cc: Geliang Tang <geliang.tang@suse.com>
Signed-off-by: Matthieu Baerts <matthieu.baerts@tessares.net>
Message-Id: <20221129142010.2886747-1-matthieu.baerts@tessares.net>