Squash to "mptcp: add MPTCP_INFO getsockopt"
This fix compilation errors reported by Geliang and Intel's 0-DAY CI
Kernel Test Service:

   ./usr/include/linux/mptcp.h:207:19: error: field has incomplete type 'struct sockaddr'
                   struct sockaddr sa_local;
                                   ^
   ./usr/include/linux/mptcp.h:209:23: error: field has incomplete type 'struct sockaddr_in6'
                   struct sockaddr_in6 sin6_local;
                                       ^
   ./usr/include/linux/mptcp.h:210:27: error: field has incomplete type 'struct sockaddr_storage'
                   struct sockaddr_storage ss_local;
                                           ^
   ./usr/include/linux/mptcp.h:213:19: error: field has incomplete type 'struct sockaddr'
                   struct sockaddr sa_remote;
                                   ^
   ./usr/include/linux/mptcp.h:215:23: error: field has incomplete type 'struct sockaddr_in6'
                   struct sockaddr_in6 sin6_remote;
                                       ^
   ./usr/include/linux/mptcp.h:216:27: error: field has incomplete type 'struct sockaddr_storage'
                   struct sockaddr_storage ss_remote;
                                           ^

Please note that socket.h should not be needed because it is included by
in.h. Here we explicitly add it but it can be removed if needed.

Also it seems we need to use __kernel_sockaddr_storage in uapi.

Reported-and-tested-by: Geliang Tang <geliangtang@gmail.com>
Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Matthieu Baerts <matthieu.baerts@tessares.net>