mptcp: bpf: fix compilation error
The error:

  net/mptcp/bpf.c:171:3: error: 'const struct btf_kfunc_id_set' has no member named 'check_set'
    171 |  .check_set = &bpf_mptcp_sched_kfunc_ids,
        |   ^~~~~~~~~
  net/mptcp/bpf.c:171:15: error: initialization of 'struct btf_id_set8 *' from incompatible pointer type 'struct btf_id_set *' [-Werror=incompatible-pointer-types]
    171 |  .check_set = &bpf_mptcp_sched_kfunc_ids,
        |               ^

Fixes: a4703e318432 ("bpf: Switch to new kfunc flags infrastructure")
Signed-off-by: Matthieu Baerts <matthieu.baerts@tessares.net>