mptcp: bpf: Remove redundant KF_TRUSTED_ARGS flag from all kfuncs
Similar to what has been done elsewhere.

To avoid such compilation error:

    CC      net/mptcp/bpf.o
  /tmp/cc8OwyUA.s: Assembler messages:
  /tmp/cc8OwyUA.s:50: Error: invalid operands (*ABS* and *UND* sections) for `|'

Fixes: 1a5c01d2508a ("bpf: Make KF_TRUSTED_ARGS the default for all kfuncs")
Signed-off-by: Matthieu Baerts (NGI0) <matttbe@kernel.org>