gen_initramfs.sh: use 'date -u' to get Timestamp
There exists a compilation error in the latest version of
mptcp-upstream-virtme-docker:latest:
'''
	ERROR: Timestamp out of range for cpio format
	make[4]: *** [<KERNEL_SRC>/usr/Makefile:76:
'''

The reason is the output of 'date -d0' is 'Sat Jan 1 00:00:00 UTC 0000'.
After using 'date -u', the output is correct.

Reported-by: Geliang Tang <geliang@kernel.org>
Signed-off-by: Gang Yan <yangang@kylinos.cn>
Message-ID: <20251013101946.248420-1-yangang@kylinos.cn>