mptcp: fix compilation error
Reported by the CI:

  net/mptcp/fastopen.c: In function 'mptcp_gen_msk_ackseq_fastopen':
  net/mptcp/fastopen.c:24:30: error: implicit declaration of function 'MPTCP_SKB_CB' [-Werror=implicit-function-declaration]
     24 |                 WARN_ON_ONCE(MPTCP_SKB_CB(skb)->end_seq);
        |                              ^~~~~~~~~~~~

Fixes: c0cda5b7f267 ("Squash-to: "mptcp: implement delayed seq generation for passive fastopen"")
Signed-off-by: Matthieu Baerts <matthieu.baerts@tessares.net>