Squash to "bpf: add bpf_skc_to_mptcp_sock_proto"
Fix the build breaks reported by kernel test robot:

[mptcp:export 32/40] ld.lld: error: undefined symbol: bpf_mptcp_sock_from_subflow
[mptcp:export 32/40] filter.c:undefined reference to `bpf_mptcp_sock_from_subflow'

- add defined(CONFIG_BPF_JIT) too.
- move bpf_mptcp_sock_from_subflow from bpf.h to mptcp.h.

base-commit: export/20220329T195411

Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Geliang Tang <geliang.tang@suse.com>
Signed-off-by: Matthieu Baerts <matthieu.baerts@tessares.net>