Reapply "selftests: bpf: fix recent compilation errors"
This reverts commit 7ed4d730528aa47222c5ba1c9584efe174951a3d.

There are still some issues apparently, one of the 4 builds had the
following error:

    CLNG-BPF [test_progs] cgrp_ls_attach_cgroup.bpf.o
  progs/cgroup_read_xattr.c:36:2: error: call to undeclared function 'bpf_cgroup_release'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
     36 |         bpf_cgroup_release(cgrp);
        |         ^
  progs/cgroup_read_xattr.c:36:2: note: did you mean 'bpf_ct_release'?
  tools/include/vmlinux.h:119946:13: note: 'bpf_ct_release' declared here
   119946 | extern void bpf_ct_release(struct nf_conn *nfct) __weak __ksym;
          |             ^
  progs/cgroup_read_xattr.c:52:2: error: call to undeclared function 'bpf_cgroup_release'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
     52 |         bpf_cgroup_release(cgrp);
        |         ^
  progs/cgroup_read_xattr.c:71:2: error: call to undeclared function 'bpf_cgroup_release'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
     71 |         bpf_cgroup_release(cgrp);
        |         ^
  progs/cgroup_read_xattr.c:90:2: error: call to undeclared function 'bpf_cgroup_release'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
     90 |         bpf_cgroup_release(cgrp);
        |         ^
  progs/cgroup_read_xattr.c:110:2: error: call to undeclared function 'bpf_cgroup_release'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    110 |         bpf_cgroup_release(cgrp);
        |         ^
  progs/cgroup_read_xattr.c:132:2: error: call to undeclared function 'bpf_cgroup_release'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    132 |         bpf_cgroup_release(ancestor);
        |         ^
  progs/cgroup_read_xattr.c:154:2: error: call to undeclared function 'bpf_cgroup_release'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    154 |         bpf_cgroup_release(ancestor);
        |         ^
  7 errors generated.

Signed-off-by: Matthieu Baerts (NGI0) <matttbe@kernel.org>