mptcp: fix compilation error
  error: label 'out' defined but not used [-Werror=unused-label]

Fixes: 2517e6c6c7cd ("mptcp: improve last merge conflict resolution")
Signed-off-by: Matthieu Baerts <matthieu.baerts@tessares.net>