Squash to "mptcp: remote addresses fullmesh"
This fixes 'unused-but-set-variable' warning.

Jenkins Tessares reported [1] this error:

  net/mptcp/pm_netlink.c: In function 'fill_remote_addresses_vec':
  net/mptcp/pm_netlink.c:435:23: error: variable 'pernet' set but not  used [-Werror=unused-but-set-variable]
    435 |  struct pm_nl_pernet *pernet;
        |                       ^~~~~~
  cc1: all warnings being treated as errors

Indeed, this variable is defined and set but not used. We can remove it.

[1] https://github.com/multipath-tcp/mptcp_net-next/actions/runs/1096568275

Reported-by: Jenkins Tessares <kernel-dev@tessares.net>
Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Matthieu Baerts <matthieu.baerts@tessares.net>
Acked-by: Geliang Tang <geliangtang@xiaomi.com>
Signed-off-by: Matthieu Baerts <matthieu.baerts@tessares.net>