Squash to "mptcp: drop *_max fields in mptcp_pm_data"
We need to export these functions that are also used in mptcp_diag.c
which can be part of a separated module.

We can then avoid these errors:

  ERROR: modpost: "mptcp_pm_get_add_addr_accept_max" [net/mptcp/mptcp_diag.ko] undefined!
  ERROR: modpost: "mptcp_pm_get_add_addr_signal_max" [net/mptcp/mptcp_diag.ko] undefined!
  ERROR: modpost: "mptcp_pm_get_subflows_max" [net/mptcp/mptcp_diag.ko] undefined!

Signed-off-by: Matthieu Baerts <matthieu.baerts@tessares.net>